# Generated by Django 3.0.7 on 2020-07-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterincome', '0002_auto_20200704_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='support',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
