# Generated by Django 3.0.7 on 2020-07-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterincome', '0004_auto_20200712_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Entertainment', 'Entertainment'), ('Politics', 'Politics'), ('Education', 'Education'), ('Health', 'Health'), ('Business', 'Business')], max_length=25),
        ),
    ]
