# Generated by Django 3.0.7 on 2020-07-17 18:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterincome', '0005_auto_20200712_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Entertainment', 'Entertainment'), ('Politics', 'Politics'), ('Education', 'Education'), ('Health', 'Health'), ('Business', 'Business'), ('Other', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='post_image'),
        ),
        migrations.AlterField(
            model_name='sponsoredpost',
            name='feature_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='feature_image'),
        ),
    ]
