# Generated by Django 3.0.7 on 2020-07-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterincome', '0006_auto_20200717_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(null=True, upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='sponsoredpost',
            name='feature_image',
            field=models.ImageField(null=True, upload_to='feature_image'),
        ),
    ]
