# Generated by Django 3.0.7 on 2020-06-23 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField()),
                ('account_details', models.TextField()),
                ('activities_earning_to_withdraw', models.PositiveIntegerField(null=True)),
                ('guider_bonus_to_withdraw', models.PositiveIntegerField(null=True)),
                ('withdrawn', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='images/')),
                ('facebook_link', models.URLField(unique=True)),
                ('account_name', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('profile_created', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnings_review', models.BooleanField(null=True)),
                ('sponsored_post_verification', models.BooleanField(null=True)),
                ('details_cross_check', models.BooleanField(null=True)),
                ('last_payment_upload', models.BooleanField(null=True)),
                ('deduction', models.BooleanField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('made', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_login', models.PositiveIntegerField(default=0)),
                ('news_earned', models.IntegerField(default=0)),
                ('approved_post', models.PositiveIntegerField(default=0)),
                ('activities_earning', models.IntegerField(default=0)),
                ('guider_bonus', models.IntegerField(default=0)),
                ('activities_earning_withdrawn', models.IntegerField(default=0)),
                ('activities_earning_remain', models.IntegerField(default=0)),
                ('guider_bonus_withdrawn', models.IntegerField(default=0)),
                ('guider_bonus_remain', models.IntegerField(default=0)),
                ('last_login', models.IntegerField(default=20200000)),
                ('post_pk', models.PositiveIntegerField(default=0)),
                ('news_pk', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20, unique=True)),
                ('guider', models.CharField(default='none', max_length=150)),
                ('is_activated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
