# Generated by Django 3.0.7 on 2020-07-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200709_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='activities_earning',
            new_name='activities_earning_remain',
        ),
        migrations.RenameField(
            model_name='withdrawal',
            old_name='guider_bonus',
            new_name='guider_bonus_remain',
        ),
    ]
