# Generated by Django 3.0.7 on 2020-07-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200709_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='activities_earning_remain',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='guider_bonus_remain',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='sponsored_post_checked',
        ),
    ]
