# Generated by Django 3.0.7 on 2020-07-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200709_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='withdrawn',
            new_name='sponsored_post_checked',
        ),
    ]
