# Generated by Django 3.0.7 on 2020-07-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200711_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='payment_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
