# Generated by Django 3.0.7 on 2020-07-25 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_auto_20200723_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='BronzeCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20, unique=True)),
                ('guider', models.CharField(default='none', max_length=150)),
                ('is_activated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bronze', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiamondCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20, unique=True)),
                ('guider', models.CharField(default='none', max_length=150)),
                ('is_activated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diamond', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoldCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20, unique=True)),
                ('guider', models.CharField(default='none', max_length=150)),
                ('is_activated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gold', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SilverCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20, unique=True)),
                ('guider', models.CharField(default='none', max_length=150)),
                ('is_activated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='silver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UltimateCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20, unique=True)),
                ('guider', models.CharField(default='none', max_length=150)),
                ('is_activated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ultimate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='regularcoupon',
            name='user',
        ),
        migrations.RenameField(
            model_name='earning',
            old_name='activities_earning',
            new_name='daily_earning',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='activities_earning_remain',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='activities_earning_withdrawn',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='approved_post',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='daily_login',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='guider_bonus_remain',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='guider_bonus_withdrawn',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='news_earned',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='news_pk',
        ),
        migrations.DeleteModel(
            name='CouponCode',
        ),
        migrations.DeleteModel(
            name='RegularCoupon',
        ),
    ]
