# Generated by Django 3.0.7 on 2020-07-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200725_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='bronzecoupon',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='diamondcoupon',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='goldcoupon',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='silvercoupon',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ultimatecoupon',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
