# Generated by Django 3.0.7 on 2020-07-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200725_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='withdrawal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
